// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uxemytoreqeasqalfcmv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV4ZW15dG9yZXFlYXNxYWxmY212Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4Mjk1MDIsImV4cCI6MjA2NTQwNTUwMn0.miDBHuN6_cbTRo4qXE8ebJq0pBqGzLMZdONx3_7X3Mw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);